# Generated by Django 3.0.8 on 2020-07-07 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='uploaded_on',
            field=models.DateTimeField(auto_now_add=True, default='2020-12-01'),
            preserve_default=False,
        ),
    ]
